**Lomik_XP** (Программист)  

Человек, который смог восстановить исходный код старого Manga Watcher 1.1.6,
тем самым дав вторую жизнь проекту (оригинальный автор бросил разработку).
За существование новой гибридной версии Manga Watcher X благодарим его.

Начиная с версии 3.1.6.0 - Реклама - удалена, но
Вы можете поддержать разработку приложения
оказав финансовую поддержку разработчику перечислив желаемую сумму на один из кошельков


Пожертвовать разработчику используя удобную вам систему оплаты:

 WebMoney
WMР (₽) R325037184740
WMZ ($) Z354550177554
WME (€) E610013029880

 ЮMoney
Номер кошелька:   410012999774465

Patreon
https://www.patreon.com/lomik_xp
____________________________________________
**Veopot**
(В данный момент все, кроме работы Lomik_XP)  

Разработчик парсеров, тестер, админ официальной группы в VK

Обо мне я Владимир Топоев под ником Veopot
увлекся Manga Watcher X в 2013 и с того времени до сих пор пользуюсь, поддерживаю
программу (парсеры),

за разработку приложения отвечает разработчик Lomik_XP

Как подержать, можно добрым словом либо через Донат: 
Альфа-банк Номер карты:   5559-4941-7018-4815
